### ISSUE TITLE
Initialization

### ISSUE THREAD

**Issue by egpbos** [conda-forge/mysql-feedstock#3]
After installing, running mysqld doesn't actually work yet. In most packaging solutions, the package sets up the data directory automatically (https://dev.mysql.com/doc/refman/5.7/en/postinstallation.html). I've tried doing this manually, but am having trouble getting everything to work.

Is there some easier way of starting the daemon that I'm overlooking?

**Comment by beckermr** [comment]
So conda supports activation scripts which get run when the package is activated. This would work for the daemon. 

I would be very careful about storing data in the conda prefix. If you ever remove the environment, then the data would be gone!

Here is the homebrew recipe for reference: https://github.com/Homebrew/homebrew-core/blob/master/Formula/mysql.rb

**Comment by egpbos** [comment]
The only issue with activation scripts is that they don't get activated for the root environment. But it might still make sense to do it, and just activate manually when installed in a root env.

**Comment by beckermr** [comment]
Right. Working in an inactivated env is not a great idea anyways. I always make a default one and work in it for this exact reason

**Comment by egpbos** [comment]
Hm, so where to put the default data directory? It's a bit uncommon for conda packages to install things outside of their environments, I'd say, even though that would be the most logical place to put it, I think (e.g. /var/mysql). I don't think you can even do this in the build phase, right? So then initialization would have to be done purely from the activation script, and there would have to be some checks to see whether a directory is already present.

Also, what should we do if multiple environments with mysql in it get activated?

I'm starting to think it's actually better to leave initialization and running to the user. But I'm open to solutions.

**Comment by beckermr** [comment]
> I'm starting to think it's actually better to leave initialization and running to the user. But I'm open to solutions.

Yuuuup. This is where I ended up too!

**Comment by egpbos** [comment]
Let's leave it at that then, feel free to close.
