### ISSUE TITLE
Strict pinning cases package incompatibility

### ISSUE THREAD

**Issue by izahn** [conda-forge/mysql-feedstock#48]
Since the recent release of `r-base=4.1.0` I've been having trouble creating environments with `r-base` and other packages that depend on `mysql`. For example:

```
$ mamba create -q -n aaa qt=5.12.9 r-base=4.1.0 --dry-run                                                                                          (mamba) 
Encountered problems while solving:
  - package qt-5.12.9-h1f2b2cb_0 requires mysql-libs >=8.0.21,<8.0.22.0a0, but none of the providers can be installed
```

Over in https://github.com/conda-forge/qt-feedstock/pull/194#issuecomment-858667742 @isuruf suggested that this is because `mysql` is pinned to strictly. Can the version pinning here be relaxed so that everything depending on `mysql` doesn't have to be rebuilt for every `mysql` version?

**Comment by nehaljwani** [comment]
I do not know about the abi compatibility across various versions for mysql, which is why I've put it too strict. I've opened https://github.com/lvc/upstream-tracker/issues/94 for getting info on the 8.* series.

Also, looking at https://abi-laboratory.pro/index.php?view=compat_report&l=mysql-connector-c&v1=6.1.5&v2=6.1.6&obj=50437&kind=abi#Removed, they had some scary symbol removals in patch releases.

**Comment by isuruf** [comment]
https://mysqlserverteam.com/the-client-library-part-2-the-version-number/ says that they only add symbols with the same SOVERSION and will change the SOVERSION if symbols are removed.

I checked and all `mysql-libs` have SOVERSION 21.

**Comment by nehaljwani** [comment]
They did bump the `SONAME` while going from 5.6 to 5.7. So a `pin_subpackage(max_pin='x')` run_exports can be ruled out easily. 

@isuruf Are you suggesting to assume that they won't bump `SONAME` in a patch release of mysql, and we should be okay with: `pin_subpackage(max_pin='x.x')` ?

**Comment by isuruf** [comment]
yes

**Comment by isuruf** [comment]
@nehaljwani's PR should fix new packages, but for packages that are already built like qt, we need to hot fix the requirements.
@izahn, can you send a PR to conda-forge-repodata-patches-feedstock to fix the requirements? For eg: https://github.com/conda-forge/conda-forge-repodata-patches-feedstock/blob/master/recipe/gen_patch_json.py#L650-L652

**Comment by izahn** [comment]
I opened https://github.com/conda-forge/conda-forge-repodata-patches-feedstock/pull/143
