### ISSUE TITLE
MySQL 8 package

### ISSUE THREAD

**Issue by AgrawalAmey** [conda-forge/mysql-feedstock#6]
Can we have a separate feedstock for MySQL 8?

**Comment by beckermr** [comment]
why?

**Comment by AgrawalAmey** [comment]
@beckermr there doesn't seem to be any mysql package available for conda.

**Comment by beckermr** [comment]
there is mysql 5 here

we can upgrade this feedstock to 8 

prs welcome!

**Comment by AgrawalAmey** [comment]
Ohh okay, I thought since mysql 5.7 is still in use, this was intentional. Will create a PR

**Comment by beckermr** [comment]
we can make another branch for 5.7 if people want updates

**Comment by beckermr** [comment]
coordinate with @nehaljwani as he had some great ideas for making this build better

**Comment by AgrawalAmey** [comment]
sure, @beckermr. Thanks for the pointer.

**Comment by nehaljwani** [comment]
So, building is not that hard. Splitting it is.

On Fedora, we have:
```
community-mysql | MySQL client programs and shared libraries
community-mysql-common | The shared files required for MySQL server and client
community-mysql-devel | Files for development of MySQL applications
community-mysql-errmsg | The error messages files required by MySQL server
community-mysql-libs | The shared libraries required for MySQL clients
community-mysql-server | The MySQL server and related files
community-mysql-test | The test suite distributed with MySQL
```

My intent is to split the package like this:
```
mysql-plugins -> all plugins
mysql-libs -> all shared libraries
mysql-common -> shared files b/w server and client
mysql-devel -> header files and dependency on mysql-libs
mysql -> server binaries with a dependency on mysql-plugins and mysql-libs and mysql-common
```

Then mysql-connector-python and other mysql (C/C++/python/whatnot) clients can then start depending on mysql-devel (during build) which will have a run_exports on myql-libs. If these want plugins, they can optionally depend on that too.

Refer: https://src.fedoraproject.org/rpms/community-mysql/blob/f32/f/community-mysql.spec for the contents for splitting
