### ISSUE TITLE
Dangling symlink to libfido2 in mysql-libs package

### ISSUE THREAD

**Issue by SylvainCorlay** [conda-forge/mysql-feedstock#73]
### Solution to issue cannot be found in the documentation.

- [X] I checked the documentation.

### Issue

On OS X, the `mysql-libs` package includes a **dangling symlink** at `$PREFIX/lib/plugin/libfido2.1.dylib` poiting at `$PREFIX/lib/libfido2.1.dylib`, which does not exist. 

This causes warnings in conda-build when building packages that depend on mysql.

### Installed packages

```shell
N/A
```

### Environment info

```shell
N/A
```

**Comment by SylvainCorlay** [comment]
cc @nehaljwani this causes warnings when building downstream packages that depend on mysql-libs.

**Comment by nehaljwani** [comment]
Resolved via https://github.com/conda-forge/mysql-feedstock/commit/e19c2803f8b67636ab26b355f5615d7f815aa3f4
